import type { AdSpec, SurfaceProfile } from '../engine/types';

export const adSpec: AdSpec = {
  id: 'nova-x-launch',
  background: '#111827',
  padding: 20,
  spacing: 12,
  elements: [
    {
      id: 'brand',
      role: 'brand',
      kind: 'logo',
      content: 'FLAM',
      minWidth: 60,
      minHeight: 24,
      priority: 1,
      canDrop: false,
      canTruncate: false,
    },
    {
      id: 'hero',
      role: 'image',
      kind: 'image',
      content: 'Nova X',
      minWidth: 100,
      minHeight: 80,
      preferredWidth: 260,
      preferredHeight: 240,
      aspectRatio: 1.4,
      priority: 3,
      canDrop: true,
      canTruncate: false,
    },
    {
      id: 'headline',
      role: 'headline',
      kind: 'text',
      content: 'Meet the new Nova X',
      minWidth: 120,
      minHeight: 42,
      preferredHeight: 72,
      priority: 10,
      canDrop: false,
      canTruncate: false,
    },
    {
      id: 'body',
      role: 'body',
      kind: 'text',
      content: 'Powerful performance, intelligent design and an experience built for every screen.',
      minWidth: 100,
      minHeight: 32,
      preferredHeight: 60,
      priority: 4,
      canDrop: true,
      canTruncate: true,
    },
    {
      id: 'price',
      role: 'price',
      kind: 'text',
      content: 'Starting at ₹49,999',
      minWidth: 100,
      minHeight: 32,
      preferredHeight: 40,
      priority: 7,
      canDrop: true,
      canTruncate: false,
    },
    {
      id: 'cta',
      role: 'cta',
      kind: 'button',
      content: 'Buy now',
      minWidth: 100,
      minHeight: 44,
      preferredWidth: 180,
      preferredHeight: 52,
      priority: 10,
      canDrop: false,
      canTruncate: false,
    },
  ],
};

export const surfaces: SurfaceProfile[] = [
  {
    id: 'mobile-portrait',
    name: 'Mobile Portrait',
    width: 390,
    height: 844,
    safeArea: { top: 24, right: 12, bottom: 24, left: 12 },
    minTapTarget: 44,
    minTextSize: 14,
    input: 'touch',
  },
  {
    id: 'mobile-landscape',
    name: 'Mobile Landscape',
    width: 844,
    height: 390,
    safeArea: { top: 12, right: 24, bottom: 12, left: 24 },
    minTapTarget: 44,
    minTextSize: 14,
    input: 'touch',
  },
  {
    id: 'broadcast-lower-third',
    name: 'Broadcast Lower Third',
    width: 1280,
    height: 360,
    safeArea: { top: 20, right: 40, bottom: 20, left: 40 },
    minTapTarget: 0,
    minTextSize: 28,
    input: 'remote',
  },
  {
    id: 'square-kiosk',
    name: 'Square Kiosk',
    width: 700,
    height: 700,
    safeArea: { top: 24, right: 24, bottom: 24, left: 24 },
    minTapTarget: 48,
    minTextSize: 18,
    input: 'touch',
  },
  {
    id: 'tiny-kiosk',
    name: 'Constrained Kiosk',
    width: 320,
    height: 260,
    safeArea: { top: 12, right: 12, bottom: 12, left: 12 },
    minTapTarget: 44,
    minTextSize: 16,
    input: 'touch',
    maxElements: 5,
  },
];
